### PR TITLE
fix: Zitadel provider fails to upload images using resource "zitadel_label_policy" #152

### PR DESCRIPTION
**Pull request by akinsella-socrate**
This pull request refers to the issue #152 (Zitadel provider fails to upload images using resource "zitadel_label_policy")
### Definition of Ready

- [x] Short description of the feature/issue is added in the pr description
- [x] PR is linked to the corresponding user story ( https://github.com/zitadel/terraform-provider-zitadel/issues/152 )
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [x] No debug or dead code
- [x] My code has no repetitions
- [ ] All non-functional requirements are met
- [ ] The generic lifecycle acceptance test passes for affected resources.
- [ ] Examples are up-to-date and meaningful. The provider version is incremented.
- [ ] Docs are generated.
- [ ] Code is generated where possible.

### CODE REVIEW

**Review by stebenz — APPROVED** [review]

**Comment by stebenz** [comment]
@akinsella-socrate could you please merge back the main branch?

**Comment by hifabienne** [comment]
@akinsella-socrate Can you please merge the main into your branch? Or give us the rights to do that?

**Comment by hifabienne** [comment]
Hei @akinsella-socrate 
We will close the pr by the end of march, if we do not get an updated version.
You can always send a new pr, but we are not able to merge it at the moment as we can't merge the main ourselfv into your branch.

**Comment by eliobischof** [comment]
Closing in favor of #166

**Pull request closed without merging**
