### PR TITLE
Refer to smtp_config by ID

### LINKED ISSUE #180: Update to `zitadel_smtp_config` fails
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Version

provider registry.terraform.io/zitadel/zitadel v1.2.0

### ZITADEL Version

cloud

### Describe the problem caused by this bug

```
╷
│ Error: failed to update smtp config: rpc error: code = InvalidArgument desc = invalid UpdateSMTPConfigRequest.Id: value length must be between 1 and 100 runes, inclusive
│ 
│   with zitadel_smtp_config.brevo,
│   on auth.tf line 92, in resource "zitadel_smtp_config" "brevo":
│   92: resource "zitadel_smtp_config" "brevo" {
│ 
╵
```

### To reproduce

I'm not sure.

### Screenshots

_No response_

### Expected behavior

As a user of the terraform provider and the `zitadel_smtp_config` resource, I want to change any property that is within the specs and that isn't documented as read-only without any error.

### Relevant Configuration

```
resource "zitadel_smtp_config" "brevo" {
  sender_address = "${var.mail_sender_userpart}@${data.cloudflare_zone.main.name}"
  sender_name    = var.mail_sender_name
  host           = var.brevo_smtp_host
  tls            = true
  user           = var.brevo_smtp_user
  password       = var.brevo_zitadel_smtp_key
}
```

### Additional Context

To me, it looks like the API changed and that there is now more than one SMTP configuration supported at a time, which it wasn't before. The terraform resource still only knows how to deal with just one SMTP configuration, not many.

### PR DESCRIPTION
**Pull request by cimnine**
This updates the terraform provider to refer to the SMTP Configuration by their IDs. **This is a breaking change!** Previous SMTP configs need to be removed from the state and re-imported with their proper resource ID.

Fixes #180

### Todo

- [ ] Fix import acceptance test

### Definition of Ready

- [x] Short description of the feature/issue is added in the pr description
- [x] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [x] No debug or dead code
- [x] My code has no repetitions
- [x] All non-functional requirements are met
- [ ] The generic lifecycle acceptance test passes for affected resources.
- [x] Examples are up-to-date and meaningful. The provider version is incremented.
- [ ] Docs are generated.
- [x] Code is generated where possible.

### CODE REVIEW

**Comment by cimnine** [comment]
The test currently fails as follows:

```text
=== RUN   TestAccSMTPConfig
=== PAUSE TestAccSMTPConfig
=== CONT  TestAccSMTPConfig
    lifecyletest.go:73: Step 5/7 error running import: exit status 1
        
        Error: Cannot import non-existent remote object
        
        While attempting to import an existing object to
        "zitadel_smtp_config.default", the provider detected that no object exists
        with the given id. Only pre-existing objects can be imported; check that the
        id is correct and that it is associated with the provider's configured region
        or endpoint, or use "terraform apply" to create a new remote object for this
        resource.
        
--- FAIL: TestAccSMTPConfig (4.62s)
```

I'm not sure how to proceed. There is probably no default SMTP config anymore, so to import a default SMTP config, one would have to be created beforehand. Is this the correct assumption and how to do that?

**Comment by cimnine** [comment]
For reference: Via Discord _Migual A. C_ suggested that this resource should also active the SMTP configuration:

> For your code I'd add the followint to the smtpconfig/funcs.go to activate the provider after it has been created: 
> ```go
>     _, err = client.ActivateSMTPConfig(ctx, &admin.ActivateSMTPConfigRequest{Id: resp.Id})
>     if err != nil {
>         return diag.Errorf("failed to activate smtp config: %v", err)
>     }
> ```

I don't believe that this is a good idea, however:

> I believe the activate part should be a new independent resource.
> Otherwise, if there are multiple parallel configurations, it will never be deterministic which configuration is currently active.

There could also be an `is_active` flag on the `zitadel_smtp_config` resource. But it would be hard to enforce that only one `zitadel_smtp_config` has the `is_active=true`:

> The benefit of an independent resource compared to an `is_active` flag (or similar) is, that with the resource we can use the internal terraform ID to ensure that there is only one zitadel_active_smtp_config (or whatever the name shall be).

**Comment by stebenz** [comment]
HI @cimnine, I took the liberty and included this changes in the new v2.0.0 release, as it was necessary to include it to upgrade zitadel/zitadel-go dependency to v3.
I will close this as it is still a draft, can you check if your problem is solved with the new verison? The SMTP config has be imported again unfortunately.

**Comment by cimnine** [comment]
I can't check, as I run into https://github.com/zitadel/terraform-provider-zitadel/issues/195 when trying.

**Comment by cimnine** [comment]
@stebenz I believe [the resource's documentation](https://registry.terraform.io/providers/zitadel/zitadel/latest/docs/resources/smtp_config) is wrong for the import:

```
# The resource can be imported using the ID format `<id[:password]>`, e.g.
terraform import zitadel_smtp_config.imported '123456789012345678:p4ssw0rd'
```

But other than that, it works for me.

**Pull request closed without merging**
